/// Call-sound asset paths (relative to the Flutter `assets/` root).
/// Used by both native ([AssetSource]) and web (URL under `/assets/…`).

const incomingCallAssetMp3 = 'sounds/incoming_call.mp3';
const incomingCallAssetWav = 'sounds/incoming_call.wav';

/// Classical pieces for outgoing ringback — one is picked at random each time.
const outgoingCallAssets = <String>[
  'sounds/outgoing/01.mp3',
  'sounds/outgoing/02.mp3',
  'sounds/outgoing/03.mp3',
  'sounds/outgoing/04.mp3',
  'sounds/outgoing/05.mp3',
  'sounds/outgoing/06.mp3',
  'sounds/outgoing/07.mp3',
  'sounds/outgoing/08.mp3',
  'sounds/outgoing/09.mp3',
  'sounds/outgoing/10.mp3',
  'sounds/outgoing/11.mp3',
  'sounds/outgoing/12.mp3',
  'sounds/outgoing/13.mp3',
  'sounds/outgoing/14.mp3',
  'sounds/outgoing/15.mp3',
  'sounds/outgoing/16.mp3',
  'sounds/outgoing/17.mp3',
  'sounds/outgoing/18.mp3',
  'sounds/outgoing/19.mp3',
  'sounds/outgoing/20.mp3',
  'sounds/outgoing/21.mp3',
  'sounds/outgoing/22.mp3',
  'sounds/outgoing/23.mp3',
  'sounds/outgoing/24.mp3',
  'sounds/outgoing/25.mp3',
  'sounds/outgoing/26.mp3',
  'sounds/outgoing/27.mp3',
  'sounds/outgoing/28.mp3',
  'sounds/outgoing/29.mp3',
  'sounds/outgoing/30.mp3',
  'sounds/outgoing/31.mp3',
  'sounds/outgoing/32.mp3',
  'sounds/outgoing/33.mp3',
  'sounds/outgoing/34.mp3',
  'sounds/outgoing/35.mp3',
  'sounds/outgoing/36.mp3',
  'sounds/outgoing/37.mp3',
  'sounds/outgoing/38.mp3',
  'sounds/outgoing/39.mp3',
  'sounds/outgoing/40.mp3',
  'sounds/outgoing/41.mp3',
  'sounds/outgoing/42.mp3',
  'sounds/outgoing/43.mp3',
  'sounds/outgoing/44.mp3',
  'sounds/outgoing/45.mp3',
  'sounds/outgoing/46.mp3',
  'sounds/outgoing/47.mp3',
  'sounds/outgoing/48.mp3',
  'sounds/outgoing/49.mp3',
  'sounds/outgoing/50.mp3',
  'sounds/outgoing/51.mp3',
  'sounds/outgoing/52.mp3',
  'sounds/outgoing/53.mp3',
  'sounds/outgoing/54.mp3',
  'sounds/outgoing/55.mp3',
  'sounds/outgoing/56.mp3',
  'sounds/outgoing/57.mp3',
  'sounds/outgoing/58.mp3',
];
